var movies = [
'A Glimpse Inside the Mind of Charles Swan III',
'Ginger & Rosa',
'Spring Breakers',
'The Bling Ring',
'The Spectacular Now',
'Under the Skin',
'Locke',
'Obvious Child',
'The Rover',
'Life After Beth',
'Laggies',
'Revenge of the Green Dragons',
'The Captive',
'A Most Violent Year',
'Son of a Gun',
'Enemy',
'While We\'re Young',
'Cut Bank',
'Ex Machina',
'Tusk',
'Slow West',
'Barely Lethal',
'Amy',
'The End of the Tour',
'Dark Places',
'Mississippi Grind',
'Room',
'Mojave',
'The Witch',
'Remember',
'Krisha',
'Hereditary',
'The Adderall Diaries',
'De Palma',
'Swiss Army Men',
'Equals',
'Into the Forest',
'Morris from America',
'The Sea of Trees',
'American Honey',
'Moonlight',
'Oasis: Supersonic',
'The Monster',
'20th Century Women',
'Trespass Against Us',
'The Black Coat\'s Daughter',
'Free Fire',
'The Lovers',
'The Exception',
'A Ghost Story',
'Menace',
'Good time',
'Woodstock',
'The Florida Project',
'The Killing of a Sacred Deer',
'Lady Bird',
'The Disaster Artist',
'The Ballad of Lefty Brown',
'The Vanishing of Sidney Hall',
'The Last Movie Star',
'Lean on Pete',
'Backstabbing for Beginners',
'First Reformed',
'How to Talk to Girls at Parties',
'Woman Walks Ahead',
'Eighth Grade',
'Never Goin\' Back',
'A Prayer Before Dawn',
'Slice',
'The Children Act',
'Mid 90s',
'Outlaws',
'The Hole in the Ground',
'Climax',
'Native Son',
'Under the Silver Lake',
'Skin',
'Low Tide',
'Share',
'Gloria Bell',
'The Kill Team',
'High Life',
'The Souvenir',
'The Last Llack Man in San Fran',
'The Farewell',
'The Death of Dick Long',
'Waves',
'In Fabric',
'Uncut Gems',
'First Cow',
'The Lighthouse'
]

function newMovie() {
  var randomNumber = Math.floor(Math.random() * (movies.length));
  document.getElementById('movieDisplay').innerHTML = movies[randomNumber];
}
